version: '3'
services:
  service1:
    build:
     dockerfile: Dockerfile
     context: ./service1
    container_name: service1
    depends_on:
      - service2
    restart: always
    ports:
      - 8001:8001
    command: npm start
    networks:
      - backend

  service2:
    build:
     dockerfile: Dockerfile
     context: ./service2
    container_name: service2
    restart: always
    command: npm start
    networks:
      - backend

networks:
 backend: